mysite/input_user/urls.py
from django.conf.urls import patterns, url

from input_user import views  # pycharm shows an import error, but actually it is correct

__author__ = 'Junfeng'


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^record$', views.record, name='record'),
                       url(r'^show/(?P<user_name>.+)/$', views.show, name='show'),
                       url(r'^show$', views.showall, name='showall'),
                       url(r'^delete/(?P<user_name>.+)/$', views.delete, name='delete')
                       )

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'mysite.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^input_user/', include('input_user.urls', namespace='input_user')),
)

mysite/input_user/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10)
    followers = models.IntegerField(default=0)
    upvotes = models.IntegerField(default=0)
    thanks = models.IntegerField(default=0)
    time = models.DateTimeField('collected date')
    user_id = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.name


class Candidates(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

mysite/input_user/views.py
# Create your views here.
import time

from django.shortcuts import render

from input_user.models import Candidates
from input_user.models import Users


def index(request):
    # return HttpResponse("Hello, world. You're at the polls index.")
    return render(request, 'input_user/input.html')


def record(request):
    input_name = request.POST['name']

    candidate = Candidates.objects.filter(name=input_name)
    print(candidate)
    if len(candidate) == 0:

        candidate = Candidates(name=input_name)
        candidate.save()
    else:
        print(input_name, ' is not none')

    context = {'condidate': candidate}
    # return render(request, 'input_user/complete.html', context)
    return showall(request)


def show(request, user_name):
    # print(user_name)
    user_entry_list = Users.objects.filter(user_id=user_name)
    followers_list = []
    upvotes_list = []
    thanks_list = []
    # i = 0
    # Get the user name in zhihu
    if len(user_entry_list) > 0:
        name = user_entry_list[0].name
    else:
        name = user_name
    for user_entry in user_entry_list:
        utc_time = int(time.mktime(user_entry.time.timetuple()) * 1000)
        followers_list.append((utc_time, user_entry.followers))
        upvotes_list.append((utc_time, user_entry.upvotes))
        thanks_list.append((utc_time, user_entry.thanks))
    context = {'name': name, 'followers_list': followers_list[-50:], 'upvotes_list': upvotes_list[-50:],
               'thanks_list': thanks_list[-50:]}
    return render(request, 'input_user/display.html', context)


def showall(request):
    candidates_result = Candidates.objects.all()
    candidates_list = []
    for entry in candidates_result:
        # print(type(entry))
        temp_list = Users.objects.filter(user_id=entry.name)
        if len(temp_list) > 0:
            name = temp_list[0].name
        else:
            name = entry.name
        candidates_list.append((entry.name, name))
        # print((entry.name, name))

    # print(candidates_list)
    context = {"candidates_list": candidates_list, "name": "test"}
    return render(request, 'input_user/showall.html', context)


def delete(request, user_name):
    Candidates.objects.filter(name=user_name).delete()
    return showall(request)

mysite/input_user/templates/input_user/complete.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Successful</title>
</head>
<body>
You have successfully record the id {{ condidate.name }}, click <a href="{% url 'input_user:index' %}">here</a> to go
back to input page.
</body>
</html>

mysite/input_user/templates/input_user/display.html
<!DOCTYPE html>
<html>
<head lang="en">
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>

    <script>
        $(function () {
            $('#followers_chart').highcharts({
                chart: {
                    type: 'spline'
                },
                title: {
                    text: '{{ name }} \'s followers Stats'
                },
                subtitle: {
                    text: 'Followers, Followers, Thanks'
                },
                xAxis: {
                    type: 'datetime',
                    dateTimeLabelFormats: { // don't display the dummy year
                        minute: '%H:%M',
                        hour: '%H:%M',
                        day: '%e. %b',
                        month: '%e. %b',
                        year: '%b'
                    },
                    title: {
                        text: 'Date'
                    }
                },
                yAxis: {
                    title: {
                        text: 'Count'
                    },
                    min: 0
                },
                tooltip: {
                    headerFormat: '<b>{series.name}</b><br>',
                    pointFormat: '{point.x: %b.%e %H:%M }: {point.y} '
                },

                plotOptions: {
                    spline: {
                        marker: {
                            enabled: true
                        }
                    }
                },

                series: [{
                    name: 'Followers',
                    // Define the data points. All series have a dummy year
                    // of 1970/71 in order to be compared on the same x axis. Note
                    // that in JavaScript, months start at 0 for January, 1 for February etc.
                    data: [
                        {% for entry in followers_list %}
                            [{{entry.0}}, {{entry.1}}],
                        {% endfor %}

                    ]
                }
                ]
            });

            $('#upvotes_chart').highcharts({
                chart: {
                    type: 'spline'
                },
                title: {
                    text: '{{ name }} \'s upvotes Stats'
                },
                subtitle: {
                    text: 'Followers, Followers, Thanks'
                },
                xAxis: {
                    type: 'datetime',
                    dateTimeLabelFormats: { // don't display the dummy year
                        minute: '%H:%M',
                        hour: '%H:%M',
                        day: '%e. %b',
                        month: '%e. %b',
                        year: '%b'
                    },
                    title: {
                        text: 'Date'
                    }
                },
                yAxis: {
                    title: {
                        text: 'Count'
                    },
                    min: 0
                },
                tooltip: {
                    headerFormat: '<b>{series.name}</b><br>',
                    pointFormat: '{point.x: %b.%e %H:%M }: {point.y} '
                },

                plotOptions: {
                    spline: {
                        marker: {
                            enabled: true
                        }
                    }
                },

                series: [
                    {
                        name: 'Upvotes',

                        data: [
                            {% for entry in upvotes_list %}
                                [{{entry.0}}, {{entry.1}}],
                            {% endfor %}

                        ]
                    }
                ]
            });

            $('#thanks_chart').highcharts({
                chart: {
                    type: 'spline'
                },
                title: {
                    text: '{{ name }} \'s thanks Stats'
                },
                xAxis: {
                    type: 'datetime',
                    dateTimeLabelFormats: { // don't display the dummy year
                        minute: '%H:%M',
                        hour: '%H:%M',
                        day: '%e. %b',
                        month: '%e. %b',
                        year: '%b'
                    },
                    title: {
                        text: 'Date'
                    }
                },
                yAxis: {
                    title: {
                        text: 'Count'
                    },
                    min: 0
                },
                tooltip: {
                    headerFormat: '<b>{series.name}</b><br>',
                    pointFormat: '{point.x: %b.%e %H:%M }: {point.y} '
                },

                plotOptions: {
                    spline: {
                        marker: {
                            enabled: true
                        }
                    }
                },

                series: [
                    {
                        name: 'Thanks',

                        data: [
                            {% for entry in thanks_list %}
                                [{{entry.0}}, {{entry.1}}],
                            {% endfor %}

                        ]
                    }
                ]
            });
        });


    </script>

    <meta charset="UTF-8">
    <title>{{ name }} 's statistics</title>
</head>
<body>
<div id="followers_chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="upvotes_chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="thanks_chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
</body>
</html>

mysite/input_user/templates/input_user/input.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Input the Zhihu id you want to monitor</title>
</head>
<body>
<form action="{% url 'input_user:record' %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" id="name"/>
    <input type="submit" value="Submit"/>
</form>
</body>
</html>

mysite/input_user/templates/input_user/showall.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>All Candidates</title>
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="http://cdn.bootcss.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <h2>用户管理</h2>

    <div class="panel panel-default">
        <div class="panel-body">
            <h3>添加新用户</h3>

            <form action="{% url 'input_user:record' %}" method="post" class="form-inline">
                <div class="form-group">
                    <div class="alert alert-info" role="alert">比如，你的主页地址为<a
                            href="http://www.zhihu.com/people/incredible-vczh">http://www.zhihu.com/people/incredible-vczh</a>，则输入incredible-vczh
                    </div>
                    <label>添加用户</label>
                    {% csrf_token %}
                    <input type="text" class="form-control" name="name" placeholder="请输入用户id" id="name"/>
                    <input type="submit" class="btn btn-primary" value="提交"/>

                </div>
            </form>
        </div>
    </div>


    <div class="panel panel-default">
        <div class="panel-body">
            <h3>当前所有用户(点击查看历史记录)</h3>
            <table class="table table-striped">
                <tr>
                    <th>用户名</th>
                    <th>知乎id（点击进入主页）</th>
                    <th>操作</th>
                </tr>
                {% for entry in candidates_list %}
                    <tr>
                        <td><a href="{% url 'input_user:show' entry.0 %}">{{ entry.1 }}</a></td>
                        <td><a href="http://www.zhihu.com/people/{{ entry.0 }}">{{ entry.0 }}</a></td>
                        <td><a href="{% url 'input_user:delete' entry.0 %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>


</div>

</body>
</html>